# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrutiny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrutinyuserprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Department'),
        ),
    ]
