# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrutiny', '0002_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='app_id',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
