# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 4, 10, 13, 42, 12, 209732))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2018, 4, 20, 13, 42, 12, 209801))),
            ],
        ),
    ]
