# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='termsRead',
            field=models.BooleanField(default=False),
        ),
    ]
