# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userprofile_termsread'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.get_profilepic_path),
        ),
    ]
