# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userprofile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilePic',
        ),
    ]
