# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
