# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.4 on 2017-10-06 04:06
=======
# Generated by Django 1.11.4 on 2017-10-06 18:28
>>>>>>> 8eada21326c40a57ee8f2d5c0d3cbfc9553fc610
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20170917_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postID',
        ),
    ]
