# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appdata',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_for', models.CharField(max_length=200)),
                ('post_in', models.CharField(max_length=200)),
                ('specialize', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField()),
                ('abstract_thesis', models.TextField()),
                ('any_other_info', models.TextField()),
                ('sports_extra', models.TextField()),
                ('lang', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_exp', models.IntegerField()),
                ('teaching_data', models.TextField()),
                ('research_exp', models.IntegerField()),
                ('research_data', models.TextField()),
                ('industrial_exp', models.IntegerField()),
                ('industrial_data', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='FacUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_occ', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('pob', models.CharField(max_length=200)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('age', models.IntegerField()),
                ('permanent_addr', models.CharField(max_length=200)),
                ('correspond_addr', models.CharField(max_length=200)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies_incl', models.TextField()),
                ('obc_cert', models.FileField(upload_to='cert/')),
                ('bach_cert', models.FileField(upload_to='cert/')),
                ('mast_cert', models.FileField(upload_to='cert/')),
                ('phd_cert', models.FileField(upload_to='cert/')),
                ('others_cert', models.FileField(upload_to='cert/')),
                ('abstr_ths', models.FileField(upload_to='cert/')),
                ('ref1', models.FileField(upload_to='cert/')),
                ('ref2', models.FileField(upload_to='cert/')),
                ('ref3', models.FileField(upload_to='cert/')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent', models.TextField()),
                ('consultancy', models.TextField()),
                ('admin_resp_held', models.TextField()),
                ('minimum_pay_exp', models.IntegerField()),
                ('time_req', models.IntegerField()),
                ('honor', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_data', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_publ', models.TextField()),
                ('research_proj', models.TextField()),
                ('pg', models.IntegerField()),
                ('phd', models.IntegerField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
    ]
