# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 09:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recruit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annexure_OBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('community', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Annexure_PartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('employment_years', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Appdata',
            fields=[
                ('app_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=14)),
                ('termsRead', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('paymentUploaded', models.BooleanField(default=False)),
                ('submitDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Post')),
                ('post_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Department')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField()),
                ('abstract_thesis', models.TextField()),
                ('any_other_info', models.TextField()),
                ('sports_extra', models.TextField()),
                ('lang', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_exp', models.IntegerField()),
                ('postPhd_exp', models.IntegerField(default=0)),
                ('teaching_data', models.TextField()),
                ('research_exp', models.IntegerField()),
                ('research_data', models.TextField()),
                ('industrial_exp', models.IntegerField()),
                ('industrial_data', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='FacUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('father_occ', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_occ', models.CharField(blank=True, max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('pob', models.CharField(max_length=200)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('age', models.IntegerField()),
                ('permanent_addr', models.CharField(max_length=200)),
                ('correspond_addr', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('pwd', models.CharField(default='no', max_length=10)),
                ('aadhaarNo', models.CharField(blank=True, max_length=13)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent', models.TextField()),
                ('consultancy', models.TextField()),
                ('admin_resp_held', models.TextField()),
                ('minimum_pay_exp', models.IntegerField()),
                ('time_req', models.IntegerField()),
                ('honor', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper1', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('paper2', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('paper3', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('paper4', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('paper5', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('cvpaper', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreeType', models.CharField(max_length=10)),
                ('degreeName', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('passingYear', models.IntegerField()),
                ('marks', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=100)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_data', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_publ', models.TextField()),
                ('research_proj', models.TextField()),
                ('pg', models.IntegerField()),
                ('phd', models.IntegerField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.AddField(
            model_name='annexure_parttime',
            name='app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata'),
        ),
        migrations.AddField(
            model_name='annexure_obc',
            name='app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata'),
        ),
    ]
