# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 12:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recruit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annexure_OBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('community', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Annexure_PartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('employment_years', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Appdata',
            fields=[
                ('app_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=14)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to=recruit.models.get_profilepic_path)),
                ('termsRead', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('paymentUploaded', models.BooleanField(default=False)),
                ('submitDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Post')),
                ('post_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Department')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacheoler_degree', models.BooleanField(default=False)),
                ('bacheoler_memo', models.BooleanField(default=False)),
                ('masters_degree', models.BooleanField(default=False)),
                ('masters_memo', models.BooleanField(default=False)),
                ('caste', models.BooleanField(default=False)),
                ('qualifying_scorecard', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreeType', models.CharField(max_length=30)),
                ('degreeName', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('passingYear', models.IntegerField()),
                ('marks', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=100)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_exp', models.IntegerField()),
                ('research_exp', models.IntegerField()),
                ('industrial_exp', models.IntegerField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='FacUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('father_occ', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_occ', models.CharField(blank=True, max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('pob', models.CharField(max_length=200)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('age', models.IntegerField()),
                ('permanent_addr', models.CharField(max_length=200)),
                ('correspond_addr', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('pwd', models.CharField(default='no', max_length=10)),
                ('aadhaarNo', models.CharField(blank=True, max_length=13)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacheoler_degree', models.BooleanField(default=False)),
                ('bacheoler_memo', models.BooleanField(default=False)),
                ('masters_degree', models.BooleanField(default=False)),
                ('masters_memo', models.BooleanField(default=False)),
                ('caste', models.BooleanField(default=False)),
                ('qualifying_scorecard', models.BooleanField(default=False)),
                ('application', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposedFieldOfResearch', models.TextField(max_length=50)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='QualifyingExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QualifyingExamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifyingYear', models.IntegerField()),
                ('score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('cutoffScore', models.FloatField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.QualifyingExam')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('conference', models.TextField(max_length=50)),
                ('link', models.TextField(max_length=50)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.AddField(
            model_name='annexure_parttime',
            name='app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata'),
        ),
        migrations.AddField(
            model_name='annexure_obc',
            name='app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata'),
        ),
    ]
