# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacheoler_degree', models.BooleanField(default=False)),
                ('bacheoler_memo', models.BooleanField(default=False)),
                ('masters_degree', models.BooleanField(default=False)),
                ('masters_memo', models.BooleanField(default=False)),
                ('caste', models.BooleanField(default=False)),
                ('qualifying_scorecard', models.BooleanField(default=False)),
                ('application', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='other',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='research',
            name='app_id',
        ),
        migrations.AddField(
            model_name='appdata',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=recruit.models.get_profilepic_path),
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
    ]
