# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='scat',
            field=models.CharField(default='init', max_length=200),
            preserve_default=False,
        ),
    ]
