# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0002_acad_annex_j_acad_annex_k_acad_annex_l_acad_annex_m_acad_annex_n_acad_annex_o_acad_annex_p_acad_anne'),
    ]

    operations = [
        migrations.AddField(
            model_name='facuser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
