# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 15:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_annexure_part_time_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Intermediate',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_docpath, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='document',
            name='SSC',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_docpath, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='flag',
            name='intermediate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flag',
            name='ssc',
            field=models.BooleanField(default=False),
        ),
    ]
