# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_appdata_scat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='scat',
            field=models.CharField(default='init', max_length=200),
        ),
    ]
