# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 12:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20171010_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='papers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='research',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_docpath, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
