# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-07 06:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20180412_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='NOC',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_docpath, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='flag',
            name='noc',
            field=models.BooleanField(default=False),
        ),
    ]
