# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 16:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_flag_guidebio'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='GuideBio',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_docpath, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
