# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20170901_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='facuser',
            name='mother_occ',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
