# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_document_guidebio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='submitDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
