# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-02 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20170901_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acad_annex_z',
            old_name='total_number',
            new_name='percentage',
        ),
        migrations.AlterField(
            model_name='acad_annex_y',
            name='total_number',
            field=models.CharField(max_length=10),
        ),
    ]
