# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20171013_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexure_part_time',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
