# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20170902_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='app_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
