# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20171020_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='division',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='marks',
            field=models.CharField(max_length=50),
        ),
    ]
