# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_auto_20170902_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTaught',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('courseType', models.CharField(max_length=30)),
                ('data', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
    ]
