# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20170902_1444'),
        ('recruit', '0008_auto_20170902_1208'),
    ]

    operations = [
    ]
