# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_auto_20171025_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexure_part_time',
            name='employment_years',
            field=models.CharField(max_length=20),
        ),
    ]
