# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_auto_20171029_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
