# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_merge_20170902_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='acad_annex_z',
            name='annexure_data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='acad_annex_z',
            name='store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acad_annex_z',
            name='total_number',
            field=models.IntegerField(default=0),
        ),
    ]
