# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_merge_20170902_1636'),
        ('recruit', '0009_merge_20170902_2244'),
        ('recruit', '0009_subjecttaught'),
    ]

    operations = [
    ]
