# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0010_appdata_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='remark',
            field=models.CharField(default='', max_length=300),
        ),
    ]
