# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0012_auto_20170902_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acad_Annex_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sem', models.IntegerField(default=0)),
                ('annexure_data', models.TextField(default='')),
                ('store', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Acad_Annex_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sem', models.IntegerField(default=0)),
                ('annexure_data', models.TextField(default='')),
                ('store', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Acad_Annex_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sem', models.IntegerField(default=0)),
                ('annexure_data', models.TextField(default='')),
                ('store', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Acad_Annex_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annexure_data', models.TextField(default='')),
                ('store', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Acad_Annex_E12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sem', models.IntegerField(default=0)),
                ('annexure_data_e1', models.TextField(default='')),
                ('annexure_data_e2', models.TextField(default='')),
                ('store_e1', models.BooleanField(default=False)),
                ('store_e2', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Acad_Annex_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sem', models.IntegerField(default=0)),
                ('annexure_data', models.TextField(default='')),
                ('store', models.BooleanField(default=False)),
                ('credit_score', models.IntegerField(default=0)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Acad_Annex_G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sem', models.IntegerField(default=0)),
                ('annexure_data', models.TextField(default='')),
                ('store', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Acad_Annex_H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sem', models.IntegerField(default=0)),
                ('annexure_data', models.TextField(default='')),
                ('store', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.CreateModel(
            name='Acad_Annex_I',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sem', models.IntegerField(default=0)),
                ('annexure_data', models.TextField(default='')),
                ('store', models.BooleanField(default=False)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.AddField(
            model_name='acad_annex_j',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_k',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_l',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_m',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_q',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_q',
            name='total_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_q',
            name='total_exp_after_phd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_q',
            name='total_exp_cur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_s',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_s',
            name='extra_load',
            field=models.IntegerField(default=0),
        ),
    ]
