# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0013_auto_20170902_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='acad_annex_h',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_j',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_k',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_l',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_m',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_n',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_o',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_p',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_q',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_r',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_s',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_u',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_v',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_w1_w2',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_x',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
