# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0014_auto_20170902_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acad_annex_d',
            name='annexure_data',
        ),
        migrations.AddField(
            model_name='acad_annex_d',
            name='basic_pay_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_d',
            name='basic_pay_r',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_d',
            name='payband_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_d',
            name='payband_end_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_d',
            name='payband_end_r',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_d',
            name='payband_r',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_d',
            name='total_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_d',
            name='total_r',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_e12',
            name='annexure_data_e1',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_e12',
            name='annexure_data_e2',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_f',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
    ]
