# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0015_auto_20170903_0410'),
        ('recruit', '0010_merge_20170903_0322'),
    ]

    operations = [
    ]
