# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0017_auto_20170903_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acad_annex_w1_w2',
            old_name='store',
            new_name='store_w1',
        ),
        migrations.AddField(
            model_name='acad_annex_w1_w2',
            name='store_w2',
            field=models.BooleanField(default=False),
        ),
    ]
