# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0018_auto_20170903_0552'),
        ('recruit', '0016_merge_20170903_0457'),
    ]

    operations = [
    ]
