# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0018_auto_20170903_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acad_annex_a',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_b',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_c',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_g',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_h',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_i',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_j',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_k',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_l',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_m',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_n',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_o',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_p',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_q',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_r',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_s',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_t',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_u',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_v',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_w1_w2',
            name='annexure_data1',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_w1_w2',
            name='annexure_data2',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_x',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_y',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='acad_annex_z',
            name='annexure_data',
            field=models.TextField(default=' '),
        ),
    ]
