# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0019_auto_20170903_1110'),
        ('recruit', '0019_merge_20170903_0707'),
    ]

    operations = [
    ]
