# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0020_merge_20170903_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference_paper_sci',
            name='papers',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='external_sponsored_rnd',
            name='patents_not_pi',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='external_sponsored_rnd',
            name='projects_not_pi',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='journal_papers',
            name='papers',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='phd_completed',
            name='phds',
            field=models.TextField(default=' '),
        ),
    ]
