# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0021_auto_20170903_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acad_annex_y',
            name='annexure_data',
        ),
        migrations.AddField(
            model_name='acad_annex_y',
            name='fna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acad_annex_y',
            name='fnae',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acad_annex_y',
            name='fnasc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acad_annex_y',
            name='ieee',
            field=models.BooleanField(default=False),
        ),
    ]
