# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0021_auto_20170903_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='agp1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appdata',
            name='agp2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appdata',
            name='agp3',
            field=models.BooleanField(default=False),
        ),
    ]
