# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0022_auto_20170903_1400'),
        ('recruit', '0022_auto_20170903_1348'),
    ]

    operations = [
    ]
