# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0023_merge_20170903_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='acad_annex_y',
            name='value',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='agp1',
            field=models.BooleanField(default=True),
        ),
    ]
