# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0023_acad_annex_y_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='acad_annex_e12',
            name='total_e1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_e12',
            name='total_e2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_g',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_h',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_i',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_j',
            name='tot_sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_k',
            name='tot_sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_l',
            name='tot_sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_n',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_o',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_p',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_r',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_s',
            name='tot_extra_load',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_t',
            name='last_prom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='acad_annex_t',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_u',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_w1_w2',
            name='total_w1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_w1_w2',
            name='total_w2',
            field=models.IntegerField(default=0),
        ),
    ]
