# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0024_auto_20170903_1809'),
        ('recruit', '0023_merge_20170903_2219'),
    ]

    operations = [
    ]
