# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0025_merge_20170903_2346'),
        ('recruit', '0024_auto_20170903_1812'),
    ]

    operations = [
    ]
