# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0023_merge_20170903_1944'),
        ('recruit', '0026_merge_20170903_1843'),
    ]

    operations = [
    ]
