# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0027_merge_20170903_1955'),
        ('recruit', '0026_merge_20170904_0008'),
    ]

    operations = [
    ]
