# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0028_merge_20170903_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper1', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[recruit.models.validate])),
                ('paper2', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[recruit.models.validate])),
                ('paper3', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[recruit.models.validate])),
                ('paper4', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[recruit.models.validate])),
                ('paper5', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[recruit.models.validate])),
                ('cvpaper', models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[recruit.models.validate])),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='app_id',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
