# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0029_auto_20170904_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='acad_annex_f',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_j',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_k',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_l',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_m',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_q',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_v',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
