# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0030_auto_20170906_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acad_annex_q',
            old_name='total',
            new_name='total_mnth',
        ),
        migrations.AddField(
            model_name='acad_annex_q',
            name='total_yr',
            field=models.IntegerField(default=0),
        ),
    ]
