# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0031_auto_20170906_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acad_annex_s',
            old_name='tot_extra_load',
            new_name='avg_load',
        ),
    ]
