# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0032_appdata_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
