# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0033_auto_20170907_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appdata',
            old_name='locked',
            new_name='submitted',
        ),
    ]
