# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0034_auto_20170907_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='submitDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
