# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0035_appdata_submitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='submitDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
