# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0037_auto_20170907_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper1',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
