# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0032_auto_20170906_2024'),
        ('recruit', '0038_auto_20170907_1057'),
    ]

    operations = [
    ]
