# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 13:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0039_merge_20170907_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='facuser',
            name='aadhaarNo',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cvpaper',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper2',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper3',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper4',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper5',
            field=models.FileField(blank=True, null=True, upload_to=recruit.models.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
