# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0041_auto_20170908_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='paymentUploaded',
            field=models.BooleanField(default=False),
        ),
    ]
