# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0042_auto_20170916_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='acad_annex_x',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acad_annex_z',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
