# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0042_appdata_paymentuploaded'),
        ('recruit', '0043_auto_20170917_0145'),
    ]

    operations = [
    ]
