# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0044_merge_20170917_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acad_annex_f',
            name='credit_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_j',
            name='credit_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_k',
            name='credit_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_l',
            name='credit_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_m',
            name='credit_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_q',
            name='credit_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_s',
            name='credit_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_y',
            name='credit_score',
            field=models.FloatField(default=0),
        ),
    ]
