# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0045_auto_20170917_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acad_annex_e12',
            name='total_e1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_e12',
            name='total_e2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_f',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_g',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_h',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_i',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_j',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_k',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_l',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_m',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_n',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_o',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_p',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_r',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_t',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_u',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_v',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_w1_w2',
            name='total_w1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_w1_w2',
            name='total_w2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_x',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='acad_annex_z',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
