# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0047_auto_20170918_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degreeName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='division',
            field=models.CharField(max_length=100),
        ),
    ]
