# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0048_auto_20170919_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acad_annex_z',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
