# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0050_auto_20171007_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
