# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0052_auto_20171008_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annexure_PartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('employment_years', models.CharField(max_length=5)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Appdata')),
            ],
        ),
    ]
