# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import admin
from recruit.models import *

# Register your models here.
admin.site.register(Appdata)
admin.site.register(FacUser)
admin.site.register(Consultancy_Projects)
admin.site.register(Conference_Paper_SCI)
admin.site.register(Experience)
admin.site.register(Education)
admin.site.register(Research)
admin.site.register(Other)
admin.site.register(Paper)
admin.site.register(Qualification)
admin.site.register(External_Sponsored_RnD)
admin.site.register(PhD_Completed)
admin.site.register(Journal_Papers)
admin.site.register(Acad_Annex_E12)
admin.site.register(SubjectTaught)
admin.site.register(Acad_Annex_F)
admin.site.register(Acad_Annex_G)
admin.site.register(Acad_Annex_H)
admin.site.register(Acad_Annex_I)
admin.site.register(Acad_Annex_J)
admin.site.register(Acad_Annex_K)
admin.site.register(Acad_Annex_L)
admin.site.register(Acad_Annex_M)
admin.site.register(Acad_Annex_N)
admin.site.register(Acad_Annex_O)
admin.site.register(Acad_Annex_P)
admin.site.register(Acad_Annex_Q)
admin.site.register(Acad_Annex_R)
admin.site.register(Acad_Annex_S)
admin.site.register(Acad_Annex_T)
admin.site.register(Acad_Annex_U)
admin.site.register(Acad_Annex_V)
admin.site.register(Referral)
admin.site.register(Acad_Annex_W1_W2)
admin.site.register(Acad_Annex_X)
admin.site.register(Acad_Annex_Y)
admin.site.register(Acad_Annex_Z)
admin.site.register(Acad_Annex_A)
# admin.site.register(Experience)
