from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'academic/$', views.academic, name = 'academic'),
    url(r'^subject_ref/$',views.subject_ref,name='subject_ref'),
    url(r'^academic/annexure_a', views.annexure_a, name = 'annexure_a'),
    url(r'^academic/annexure_b', views.annexure_b, name = 'annexure_b'),
    url(r'^academic/annexure_c', views.annexure_c, name = 'annexure_c'),
    url(r'^academic/annexure_d', views.annexure_d, name = 'annexure_d'),
    url(r'^academic/annexure_e_1', views.annexure_e_1, name = 'annexure_e_1'),
    url(r'^academic/annexure_e2', views.annexure_e2, name = 'annexure_e2'),
    url(r'^academic/annexure_f', views.annexure_f, name = 'annexure_f'),
    url(r'^academic/annexure_g', views.annexure_g, name = 'annexure_g'),
    url(r'^academic/annexure_h', views.annexure_h, name = 'annexure_h'),
    url(r'^academic/annexure_i', views.annexure_i, name = 'annexure_i'),
    url(r'^academic/annexure_j', views.annexure_j, name = 'annexure_j'),
    url(r'^academic/annexure_k', views.annexure_k, name = 'annexure_k'),
    url(r'^academic/annexure_l', views.annexure_l, name = 'annexure_l'),
    url(r'^academic/annexure_m', views.annexure_m, name = 'annexure_m'),
    url(r'^academic/annexure_n', views.annexure_n, name = 'annexure_n'),
    url(r'^academic/annexure_o', views.annexure_o, name = 'annexure_o'),
    url(r'^academic/annexure_p', views.annexure_p, name = 'annexure_p'),
    url(r'^academic/annexure_q', views.annexure_q, name = 'annexure_q'),
    url(r'^academic/annexure_r', views.annexure_r, name = 'annexure_r'),
    url(r'^academic/annexure_s', views.annexure_s, name = 'annexure_s'),
    url(r'^academic/annexure_t', views.annexure_t, name = 'annexure_t'),
    url(r'^academic/annexure_u', views.annexure_u, name = 'annexure_u'),
    url(r'^academic/annexure_v', views.annexure_v, name = 'annexure_v'),
    url(r'^academic/annexure_w1', views.annexure_w1, name = 'annexure_w1'),
    url(r'^academic/annexure_w2', views.annexure_w2, name = 'annexure_w2'),
    url(r'^academic/annexure_x', views.annexure_x, name = 'annexure_x'),
    url(r'^academic/annexure_y', views.annexure_y, name = 'annexure_y'),
    url(r'^academic/annexure_z', views.annexure_z, name = 'annexure_z'),
    url(r'^printSummary/$',views.printSummary,name='printSummary'),
    url(r'^print_main_application', views.print_main_application, name = 'print_main_application'),
    url(r'^print_annexures', views.print_annexures, name = 'print_annexures'),
    url(r'^uploadPaper/(?P<papernum>[0-9]{1})/$',views.uploadPaper),
    url(r'^lockApplication/$',views.lockApplication,name='lockApplication'),
    url(r'^printAck/$',views.printAck,name='printAck'),
    url(r'^refresh/(?P<annexName>[a-z0-9_]+)/$',views.refresh),
    url(r'^uploadExpDoc/$',views.uploadExpDoc),
    url(r'^all_annexures/$',views.all_annexures),
    
]
